cascade:
  - params:
      "y": ["curl"]
    target:
      path: "**/curl/**"
      kind: page
  - params:
      "y": ["go"]
    target:
      path: "**/go/**"
      kind: page
  - params:
      "y": ["python"]
    target:
      path: "**/python/**"
      kind: page
  - params:
      "x": ["array_reverse"]
    target:
      path: "**/array_reverse"
      kind: page
  - params:
      "x": ["http_request_get"]
    target:
      path: "**/http_request_get"
      kind: page
  - params:
      "x": ["string_match_prefix"]
    target:
      path: "**/string_match_prefix"
      kind: page
