cascade:
  # Y
  - params:
      "y": ["go"]
    target:
      path: "**/go/**"
      kind: page
  - params:
      "y": ["python"]
    target:
      path: "**/python/**"
      kind: page
  # X
  - params:
      "x": ["list_reverse"]
    target:
      path: "**/list_reverse"
      kind: page
  - params:
      "x": ["string_match_prefix"]
    target:
      path: "**/string_match_prefix"
      kind: page
