#!/usr/bin/env bash
#/ Usage: cascade [FLAGS]
#/
#/ Update the cascade config file to match the current site.
#/ Uses the 'en' content as reference.
#/ See root hugo.toml for more information.
#/
#/ Flags:
#/   -f   Show this help

set -e

show_help() { grep ^#/ <"${0}" | cut -c4-; }
[ "${*}" == "-h" ] && show_help && exit 0

OUT="./config/_default/hugo.yaml"

cat > "$OUT" <<- EOF
cascade:
EOF

find content/en/y/ -mindepth 1 -type d -print0 \
    | sort --unique --zero-terminated \
    | while IFS= read -r -d '' f; do
        f=$(basename "$f")
        cat >> "$OUT" <<- EOF
  - params:
      "y": ["$f"]
    target:
      path: "**/$f/**"
      kind: page
EOF
    done

find content/en/x/ -mindepth 1 -type d -print0 \
    | sort --unique --zero-terminated \
    | while IFS= read -r -d '' f; do
        f=$(basename "$f")
        cat >> "$OUT" <<- EOF
  - params:
      "x": ["$f"]
    target:
      path: "**/$f"
      kind: page
EOF
    done
