#!/usr/bin/env bash
#/ Usage: pagefind [-w]
#/ Flags:
#/   -w  Watch changes and reload
#/   -h  Show this help

set -e

show_help() { grep ^#/ <"${0}" |cut -c4- ; }
[[ "$*" == "-h" ]] && show_help && exit 0

if [[ "$*" == "-w" ]]; then
    trap "exit 0" SIGINT SIGTERM

    while true; do
        find public | \
            entr -c \
            npx pagefind \
                --site public
    done

    exit 0
fi

npx pagefind \
    --site public
