name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "ci"
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./script/install
      - run: ./script/lint

  cascade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./script/assert-nothing-changed ./script/cascade
